### ISSUE TITLE
I/O class idle is shown as ??

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#100]
I'm using htop 1.0.3 and if I'm setting the I/O priority with ionice normally the correct value is shown in htop except for the idle class. For example executing "ionice -c 3 -p 9395" will show "??" on the related process instead of "id". But I'm not sure if this is a reading issue of htop or a writing issue of ionice.

**Comment by wolfgang42** [comment]
I've also been bothered by this, and have compiled the latest code and reproduced the issue in a debugger. The problem seems to be in [linux/LinuxProcess.c:345][]:
```c
   case IO_PRIORITY: {
      int klass = IOPriority_class(lp->ioPriority);
      if (klass == IOPRIO_CLASS_NONE) {
         // ...
      } else if (klass == IOPRIO_CLASS_BE) {
         // ...
      } else if (klass == IOPRIO_CLASS_RT) {
         // ...
      } else if (lp->ioPriority == IOPriority_Idle) {
         // ...
         snprintf(buffer, n, "id ");
      } else {
         snprintf(buffer, n, "?? ");
      }
      break;
   }
```

I've elided most of the code to make the problem clear: the other branches compare `klass` against `IOPRIO_CLASS_*`, but the idle branch compares `lp->ioPriority` to `IOPriority_Idle`. This is defined in [linux/IOPriority.c][] as a class of `IDLE` and data of `0`.  This is presumably because [ioprio_get(2)][] says &ldquo;the idle class has no class data&rdquo;; an `IOPRIO_CLASS_IDLE` process is therefore expected to have a priority of precisely `0x6000`.

However, the process that has this problem has an IO priority of `0x6007`, i.e. a class of `IDLE` but a data of *`0x7`!* I believe I've traced the source of this data back to [ionice.c:221] (from util-linux), where this value is set explicitly for `IOPRIO_CLASS_IDLE`; this is obviously intentional but I can't figure out why it would be arranged this way. The [Linux ioprio docs][] similarly describe idle as having no data but suggest setting its data to 7. The only hint I can find is a response to a 2006 LKML thread about &ldquo;[strange ioprio][]&rdquo;, which simply describes it as &ldquo;fixed priority of 7&rdquo; without going into any detail.

This is where my limited understanding of Linux kernel internals, already stretched thin, reached its breaking point. I have a suspicion that the data is ignored by the kernel, but set by ionice on the off chance it might be used in the future; if this is the case then the solution would seem to be to change the branch for `IDLE` to compare against `klass` the same as all the others. (Incidentally, it might also be a good idea in that case to change htop to *set* the IO priority to `0x6007` instead of the current `0x6000` as well.)

However it's not at all clear to me whether this is true, or if there would be some subtle implications of doing this. I'd like to help more, but I don't have enough experience with any of this to know where to go next.

[linux/LinuxProcess.c:345]: /hishamhm/htop/blob/aa813c756144fa4cf6b57439e9f02859fbf0d81d/linux/LinuxProcess.c#L345
[linux/IOPriority.c]: /hishamhm/htop/blob/26422af6088129b99864b75ed4ce5395aa578f2b/linux/IOPriority.c
[ioprio_get(2)]: http://man7.org/linux/man-pages/man2/ioprio_get.2.html
[ionice.c:221]: https://github.com/karelzak/util-linux/blob/2ba641e5f3879593e36fa84872289872a4060d03/schedutils/ionice.c#L133
[strange ioprio]: https://lkml.org/lkml/2006/3/27/31
[Linux ioprio docs]: https://github.com/torvalds/linux/blob/5924bbecd0267d87c24110cbe2041b5075173a25/Documentation/block/ioprio.txt

**Comment by hishamhm** [comment]
@wolfgang42 Thank you for your thorough investigation! I changed the behavior as you suggested.

**Comment by tomasbrod** [comment]
And what if the IO priority is 0x6008 ?

**Comment by wolfgang42** [comment]
@tomasbrod That looks like it's covered in e9ecbd05bc7230f32d87e0622bc6b0ac5632fd9f, which compares just the `klass` instead of the entire `ioPriority`.
