### ISSUE TITLE
Change Hardcoded "Black" to "Default" 

### ISSUE THREAD

**Issue by donatj** [hishamhm/htop#14]
Black on black is really hard to read - it would be better if these were the default terminal text color rather than black.

See : ![fixme](https://f.cloud.github.com/assets/133747/2106511/b6f2a59e-8fa7-11e3-8cdb-0e3fe84359c2.png)

**Comment by NoICE** [comment]
Solarized Dark also uses "dark", nearly black color for black color. As it should. For example, if you look at midnight commander, it uses this black color (the normal, non-bright one) for it's function keys at the bottom. If I set the normal bold color to something other than the default, nearly black color, it looks horrible (and it's unreadable). The reason MC does use direct black color for it's buttons is because it also uses specific color for background. And that's OK. If I as a developer of whatever CLI program want black text on blue background, that's fine.

But wanting to use "black color" on "whatever the user has as a background color" feels really wrong. In my experience, I can't think about any other program that does it.

One fix is to go ahead and set some lighter color for "bright black" in all your terminals, OR to go to Setup -> Colors and set Black Night as the theme. This theme isn't so nice, but it at least isn't so obtrusive when you use Solarized Dark in your terminal.

I just connected to many servers and started monitoring their cpu and mem usage using htop and had to switch all of them to different color scheme. (I really don't want to change solarized dark theme in my terminals, just for htop.) So I actually went searching for this issue and voila, here it is.

@hishamhm I think the real solution is to use "bright foreground" color, if you can. That would solve everything.

Anyway, thanks to all participating for htop, it's an amazing tool.

**Comment by hishamhm** [comment]
"Use bright colors for bold text" is the only way to produce several colors in a 16-color terminal, such as yellow (bold+brown) and gray (bold+black).

This issue with gray will only really go away when htop gets 256-color support. I believe most Linux terminals support this by now. I believe OS X Terminal.app does too, right?

**Comment by ytn3rd** [comment]
Old issue but this post still shows up high in google search results. For anyone else having this problem in macOS terminal the easy fix is to open preferences -> profiles and select your terminal profile and in the text settings enable "Use bright colours for bold text"

<img width="956" alt="screen shot 2017-11-27 at 9 58 52 am" src="https://user-images.githubusercontent.com/904737/33245277-9d130a70-d359-11e7-80f0-694b096f3f7a.png">

**Comment by NoICE** [comment]
@ytn3rd this works in Terminal app but doesn't work for iTerm for example. I use Solarized Dark theme in both terminals.

**Comment by ytn3rd** [comment]
This is true, though I never bothered switching to a different terminal app (yet).

**Comment by kkonevets** [comment]
@ytn3rd thanks, this helps on mac!

**Comment by andreasvc** [comment]
I think there really is a bug here. See this message: [1]

> htop is buggy for using "bold" when it means "bright".

Anyone who configures their terminal to not show bold as bright colors, but actually as bold font, will run into this bug. There must be a proper way to display bright colors that doesn't depend on the confusion of "bold as bright".

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793106#39

**Comment by imran1008** [comment]
This is an old issue but it's still a common problem. You can change the color scheme in htop by using F2, and moving down to colors. I'm using alacritty as my terminal and my terminal background is dark. the htop theme "Broken Gray" seems to work the best.
