### ISSUE TITLE
The memory line color goes too far

### ISSUE THREAD

**Issue by AXDOOMER** [hishamhm/htop#167]
I don't know if it happens with the other lines, but when the "Mem" line is full, the color of the slash and the first number changes. While fixing this, you should check to see if there's the same bug with the other lines. 
![htop](https://cloud.githubusercontent.com/assets/6194072/6187490/1dcf5088-b355-11e4-82a8-871b3c064615.png)

**Comment by hishamhm** [comment]
This is not a bug, this is by design. The bar goes up until the "]" and the gray numbers are painted "below" it (not unlike the idea [here](http://www.flamber.ru/files/photos/1175810400/1194358689_f.jpg) — this could be made more obvious if it was graphical but there's just so much we can do with text characters ;) ). Interesting that you thought that coloring "/2" was a bug but coloring "566" was normal. :)

**Comment by AXDOOMER** [comment]
Interesting. I'm amazed.

**Comment by iridos** [comment]
This is indeed very much not obvious, I also thought it's a bug. 
Makes me wonder if it would be any better if the background has the color and the characters are all white or grey (or whatever color works with most colors of the background)
