### ISSUE TITLE
Tree View & Sort by PID not Natural

### ISSUE THREAD

**Issue by Dygear** [hishamhm/htop#258]
When entering Tree View (F5), should it not also sort by PID in a natural way? I'm showing PID 1 as the first item, obviously that's correct. But the second item, is not PID 3, that's at the bottom, PID 2 is the second to last item on the list. My most recent opened process is the second item in the list. Shouldn't the most recently open process be at the bottom of the trunk, or each branch?

![htop PID order not natural](https://cloud.githubusercontent.com/assets/367860/9569800/18587f5e-4f44-11e5-9d19-91e6c890c6ba.png)

**Comment by hishamhm** [comment]
Hi, thanks for the feedback!

This is by design. I find this order as implemented (tree with items sorted by reverse PID) way more _useful_, especially when one has pages and pages of processes. The ones at the bottom are often kernel threads, and initialization processes. The stuff you're running more recently have higher PIDs, so they appear first. (PID is used as criteria because it's a stable value — having the tree order change, say, by CPU would make it jump around in strange ways.)

**Comment by hishamhm** [comment]
(Note, also, that you can invert the tree by pressing uppercase "I".)

**Comment by Dygear** [comment]
`I` doesn't quite produce the results that I want, but if this is intended by design, then I'll have to live with it. It's still head and shoulders above the regular top command.
