### ISSUE TITLE
htop 1.0.3 aborting

### ISSUE THREAD

**Issue by eQuacky** [hishamhm/htop#277]
htop 1.0.3 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace:
/usr/bin/htop[0x4096f7]
/lib/x86_64-linux-gnu/libc.so.6(+0x35180)[0x7fb319dd3180]
/lib/x86_64-linux-gnu/libc.so.6(+0x80023)[0x7fb319e1e023]
/usr/bin/htop[0x411902]
/usr/bin/htop[0x4112fc]
/usr/bin/htop(ProcessList_scan+0x53c)[0x412f0c]
/usr/bin/htop(main+0x81e)[0x40628e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fb319dbfb45]
/usr/bin/htop[0x407aeb]

Actions having done:

Surfing with qupzilla (1.8.6), probably loading virtbox (4.3.30_Debian r101610) - don't know whether it was finished while crashing of htop, icedove - idle in the backround (38.0.1).

Kernel: 4.2.0-towo.2-siduction-amd64 x86_64 (64 bit gcc: 5.2.1)
Desktop: LXQt dm: lightdm
Distro: siduction (Debian Sid)
Memory: 1913.5/3555.4MB
systemd v: 226
runlevel: 5
Gcc sys: 4.9.3 alt: 5
Client: Shell (bash 4.3.391 running in qterminal)

greetz

eQuacky

**Comment by galegosimpatico** [comment]
I run onto one like this using Debian Jessie with default bash, version 4.3.30(1)

"htop 1.0.3 aborting. Please report bug at...."

Bash ran default tmux (1.9)
I think it happened when using the binding for 'Split the current pane into two, top and bottom.'.
First crash ever since more than five years of frequent use. Greetings.

**Comment by hishamhm** [comment]
Closing since this is now outdated! htop 2.0 is out!
