### ISSUE TITLE
Feature request: filter by PGID / show tree under specific process

### ISSUE THREAD

**Issue by unhammer** [hishamhm/htop#305]
I like the tree view, and I like filtering, but they don't work well together, since I'm often interested in only the processes started by a certain process. It'd be nice to be able to either filter by PGID (even if it's only on startup, like with -u), or preferably to let filtering in the tree view also show children of the filter-match. That is, if I type "F5 F4 sshd" it'll show not just

```
  611 root       20   0 40420  1964  1928     0 S  0.0  0.1  0:00.31 ├─ /usr/bin/sshd -D
28589 root       20   0 99880  2160  2136     0 S  0.0  0.1  0:00.02 │  ├─ sshd: unhammer [priv]
28592 unhammer   20   0 99880  1064   920     0 S  0.0  0.0  0:04.38 │  │  └─ sshd: unhammer@pts/9
14831 root       20   0 99880  2480  2448     0 S  0.0  0.1  0:00.00 │  └─ sshd: unhammer [priv]
14835 unhammer   20   0 99880  2148  1960     0 S  0.0  0.1  0:04.41 │     └─ sshd: unhammer@pts/3,pts/7
```

but the full

```
  611 root       20   0 40420  1964  1928     0 S  0.0  0.1  0:00.31 ├─ /usr/bin/sshd -D
28589 root       20   0 99880  2160  2136     0 S  0.0  0.1  0:00.02 │  ├─ sshd: unhammer [priv]
28592 unhammer   20   0 99880  1064   920     0 S  0.0  0.0  0:04.38 │  │  └─ sshd: unhammer@pts/9
28593 unhammer   20   0 23004  1344  1344     0 S  0.0  0.0  0:00.11 │  │     └─ -bash
14831 root       20   0 99880  2480  2448     0 S  0.0  0.1  0:00.00 │  └─ sshd: unhammer [priv]
14835 unhammer   20   0 99880  2148  1960     0 S  0.0  0.1  0:04.41 │     └─ sshd: unhammer@pts/3,pts/7
14968 unhammer   20   0 23008  1836  1796     0 S  0.0  0.0  0:00.08 │        ├─ -bash
18653 unhammer   20   0 21340  1456  1456     0 S  0.0  0.0  0:00.00 │        │  └─ tmux
```

**Comment by yunake** [comment]
+1, this would be really useful!

**Comment by black-puppydog** [comment]
I don't see a release since this was closed, nor any commits around January 4 that would match this. I would very much like this feature. If it was closed "due to lack of interest" I'd very much like to see it reopened. :smiley: 
My use-case is this:
I work in tmux most of the time, and I like to see how my code behaves during execution.
So I have a binding in tmux that opens htop in a vsplit pane underneath my current terminal:

  > bind '~' split-window "exec htop -u $USER"

The filtering by user is a bit too broad though. I could filter it further by selecting only the PIDs underneath the pane in question and passing those to htop, but then I miss any processes that get created afterwards, most notably if I restart my script. So for that, I'd have to restart htop every time I restart my script.
This feature would let me have htop monitor always exactly what I need to see.
