### ISSUE TITLE
On OS X htop litters console log with `System Policy: deny mach-priv-task-port` messages

### ISSUE THREAD

**Issue by baburdick** [hishamhm/htop#330]
When running `htop`, a large number of messages flood the console log, differing only by port number. Here's an example message:
```
12/27/15 1:31:58.000 AM kernel[0]: Sandbox: htop(9731) System Policy: deny(1) mach-priv-task-port 61414
```

**Comment by hishamhm** [comment]
What version of htop are you running? (i.e. what's the output of `htop --version`?)

**Comment by baburdick** [comment]
I'm using the latest MacPorts package:
```
$ htop --version
htop 0.8.2.2 - (C) 2004-2008 Hisham Muhammad.
Released under the GNU GPL.
```

**Comment by kaefer** [comment]
this version is an unofficial fork way back from 2008. Please try to compile from this repo. It should work on OS X. 
Check back if this error exists and provide your OS X version in that case as well.

**Comment by claczny** [comment]
Thanks @kaefer. Worked fine for me (OS X - El Capitan 10.11.2 (15C50)), s.a. https://github.com/Homebrew/homebrew/issues/45197.
Have to run it via `sudo htop` to get all readings.

A difference I noticed is that when run using `htop`, the memory bar displays in **G**B units rather than MB, which I actually like. However, when run using `sudo htop`, it displays in **M**B units and I can't find where to change that.

**Comment by kaefer** [comment]
perfect :) I do know the homebrew issue, but I don't think there is an updated formula already as @hishamhm has not released a new version with official OS X support yet.

**Comment by hishamhm** [comment]
Thanks for confirming the fix! The new release should be coming soon! (Later this month, I hope!)

**Comment by alanhoyle** [comment]
I'm seeing this error on htop 2.0.1 from homebrew, on OSX 10.11.5

**Comment by dylanmc** [comment]
I am also seeing this error with homebrew htop 2.0.1 on 10.11.5
