### ISSUE TITLE
Colors CPU_IOWAIT and BAR_SHADOW collide in default scheme

### ISSUE THREAD

**Issue by Explorer09** [hishamhm/htop#340]
I report this issue according to tests in pull request #327.

In the default color scheme, the IO-WAIT color in CPU Meter and the BAR_SHADOW (that is, the text color on the bar where no data is filled on it) are all gray. This will not only confuse my "colored graph" in pull request #327, but also the bar meter mode as well. (Imagine, that when up to 90% of the CPU power is doing IOWAIT, can you see the IO-WAIT color covering up the "90.X%" text on the bar?)

Only in the default color scheme that I discover this problem. Other schemes (except Monochrome, in which color problems may be tolerated) are fine.

May I propose the IO-WAIT color be changed to silver (or non-bold white in some terminals) to avoid this problem?

(It's a rather simple change in CRT.c so I won't file a pull request for this.)

**Comment by Explorer09** [comment]
Attach a screenshot to give you all a better idea of what I mean:
![screenshot from 2016-01-06 13 37 00](https://cloud.githubusercontent.com/assets/2487263/12135778/025edf6c-b47b-11e5-95ab-11ab4d87e699.png)
Note: This I/O load is made up, by a stress test program named `stress` (by Amos Waterland https://packages.debian.org/stable/stress)

**Comment by hishamhm** [comment]
I/O wait is not really CPU "usage", but rather a wait, so that's why it uses the shadow color. I think the gray color is best at depicting that the CPU is not at work.

I understand what you mean when I/O wait is 90+% and you can't tell visually whether it's 95 or 100 because the color matches that of the number. But then, the visual bars are already an approximation, and I think switching I/O wait to white would be confusing.

It's a matter of weighing two conflicting design concerns, and I'll stand by the current design. So, sorry, I think I'll close this as a "wontfix".
