### ISSUE TITLE
[feature] CPU Steal time

### ISSUE THREAD

**Issue by nvtkaszpir** [hishamhm/htop#369]
I'm REALLY missing option to display CPU steal time, for example as a number or bar.

(or I'm blind)

I know there is an option to add CPU steal time to the CPU bar, but what I'm missing is a standalone, separate metric for this, not added into another metric.
top command shows this very clearly in %Cpu(s): line as the last value (if applicable of course)

**Comment by Explorer09** [comment]
"F2 Setup" -> "Display options" -> "Add guest time in CPU meter percentage".
(And by the way, leave this issue open. I personally believe there is a usability or documentation problem behind this.)

**Comment by hishamhm** [comment]
once you enable `[x] Detailed CPU Time` in <kbd>F2</kbd>`Setup` → `Display Options`, you can change the CPU meters from `[Bar]` to `[Text]` pressing <kbd>space</kbd>, then it will show `st` as a numeric entry (not displayed in the screenshot below because I'm not running any VMs).

You might have to adjust your meters accordingly to make things nicely on screen (`Blank` meters in the right may help for that).

![detail](https://cloud.githubusercontent.com/assets/245621/13026764/d5386c84-d21a-11e5-94ae-f4c707247524.png)

**Comment by nvtkaszpir** [comment]
aht that's fantastic ! :)
