### ISSUE TITLE
FreeBSD CPU usage too low

### ISSUE THREAD

**Issue by Sp1l** [hishamhm/htop#400]
Output from `top -PI`
```
last pid: 80618;  load averages:  2.24,  2.66,  1.99                                                           up 28+05:04:54  22:09:47
120 processes: 3 running, 117 sleeping
CPU 0: 23.6% user,  0.0% nice, 17.7% system,  0.0% interrupt, 58.7% idle
CPU 1: 48.8% user,  0.0% nice, 17.7% system,  0.0% interrupt, 33.5% idle
CPU 2: 45.7% user,  0.0% nice, 14.6% system,  0.0% interrupt, 39.8% idle
CPU 3: 30.7% user,  0.0% nice, 17.3% system,  0.0% interrupt, 52.0% idle
```
Output in htop
```
  1  [||||||||                                             12.1%]   Tasks: 516, 0 thr; 7 running
  2  [|||||||                                              10.0%]   Load average: 2.26 2.67 1.99
  3  [|||||                                                 7.0%]   Uptime: 28 days, 05:04:47
  4  [|||||                                                 7.5%]
```
This is during a Poudriere bulk run (2 make processes parallel, each with make -j2) on a system with 4 CPUs (2+HT)

My hunch is that this is divided by the number of CPUs.

**Comment by tcreech** [comment]
Rather than divided by `cpus`, each CPU bar seems to be somehow divided by a factor of `(cpu + cpus)`.

For example, on an 8-core machine if I load all cores (e.g., `seq $(sysctl -n hw.ncpu) | xargs -n1 -P999 yes > /dev/null`) I see bars at about 11, 10, 9, 8, 7, 7, 6 and 6% rather than all at 100%. (I.e., 100/(1+8), 100/(2+8), ..., 100/(8+8).) On a 4-core machine I see roughly 20, 16, 14, and 12%, corresponding to 100/(1+4), 100/(2+4), 100/(3+4), and 100/(4+4).

**Comment by hishamhm** [comment]
Thank you for the fix, @tcreech!!
