### ISSUE TITLE
Meter object model doesn't allow storing non-numeric states/values conveniently

### ISSUE THREAD

**Issue by Explorer09** [hishamhm/htop#499]
The current object model of Meter classes is focused too much on drawing bars and graphs and numeric values. For meters designed for non-numeric things (e.g. HostnameMeter, UnameMeter as in PR #491), or for meters that indicate more than numeric values (e.g. BatteryMeter), it will hit technical limits and make them hard to extend the functionality.

Actually this issue is filed because I do get trapped in such an object model limit when designing the Active Users Meter (see PR #494, but I tried to implement differently). I need to way to keep the list of `{user, cpu_time, ...}` records between the `Meter.updateValues()` function call and the `Object.display()` call within the `TextMeterMode_draw()` routine, but there is no easy way for this. The only things that are carried between two calls are the numeric values (stored in `Meter` struct), the numeric `total`, and the fixed-length temporary C string `buffer`. These are not enough for my case. I will need at least a RichString to, for example, mark user names that have processes in foreground, in a color different from those that have in background. Something like this:

> Users: **4**, amelie root **nojhan** explorer

This cannot be achieved within the current object model.

Another example. The version of BatteryMeter in PR #430 needs to store the state of whether AC is present, so that it would _not_ show a low battery warning color when AC is present. PR #430 abused the `Meter.values[1]` entry for this, while the `values[]` entries was supposed to store floating points instead of boolean or enum.

Third example. This limit also prevents me to paint the OS name, release, and CPU architecture string tokens into different colors in PR #491 (UnameMeter).

For now I don't know which way to workaround the problem is the best.
- Allow another structure to extend/inherit the `Meter` structure, and edit `Meter_new()` to allow allocating a derived `Meter` structure?
- Add a generic `Object` or `void` pointer into `Meter` for any non-numeric value/state, and edit `Meter_delete()` to support freeing that object?
- Extend the purpose of `Meter.drawData` pointer to store such non-numeric values/states? (Note: The `Meter.drawData` pointers are currently only used on 2 places: one is for sub-meters for individual processors within a "container" CPU meter, the others is for graph mode's `GraphData` buffer.)

I would personally dislike the `Meter.strings[]` extension as done by @nojhan in PR #494. I would prefer a more flexible solution. Please give some comments.

**Comment by hishamhm** [comment]
I'm not even sold that adding an "Active users" meter is a good idea. Just because someone submitted a PR it doesn't mean a feature will go in (especially a meter that run an extra scan over the whole process list on every refresh).

At this point I have no desire to further complicate the object model. But this is not really a bug, right? So perhaps the right place for this conversation would be the htop@freelists.org mailing list instead of the bug tracker?

**Comment by Explorer09** [comment]
Well I thought @nojhan didn't subscribe to the mailing list, so...
Anyway, feel free to mark this as a "feature request".

**Comment by nojhan** [comment]
Note that the meter will scan the process list only until its display is filled. While the worst case is still to scan the whole list, it's most probably far from the average case.
Additionally, I'm still puzzled: wouldn't it be sufficient to warn the user that it can slow down htop and let him decide if he want to use it?

Note that I've been trying to discuss this feature since 2008. I was even on the ML at some point.
