### ISSUE TITLE
Basename are miss computed in some cases

### ISSUE THREAD

**Issue by NougatRillettes** [hishamhm/htop#644]
Hi,

The identification of basenames is sometimes failing, for example line 5 of the provided screen. This leads to both a poor highlighting and wrong displaying when the option to show the full command path is not checked.

![htop](https://user-images.githubusercontent.com/1002826/27737034-ecc85fee-5da6-11e7-898c-b63d95f3c0a7.png)

I'm running Archlinux.

**Comment by hishamhm** [comment]
Please get the PID of a program that is being painted incorrectly (e.g. 1234), then run `hexdump -C /proc/1234/cmdline`

For example, on my machine right now, process 30328 is:

```
urxvt -cr green -fn *-lode sans mono-* -fb *-lode sans mono-* -fi *-lode sans mono-* -fbi *-lode sans mono-* -depth 32 -bg rgba:0000/0000/0000/e5bb -fg #bcc -sb -sr +st -sl 100000 -b 0 -tn rxvt
```

Then, `hexdump -C /proc/30328/cmdline` produces:

```
00000000  75 72 78 76 74 00 2d 63  72 00 67 72 65 65 6e 00  |urxvt.-cr.green.|
00000010  2d 66 6e 00 2a 2d 6c 6f  64 65 20 73 61 6e 73 20  |-fn.*-lode sans |
00000020  6d 6f 6e 6f 2d 2a 00 2d  66 62 00 2a 2d 6c 6f 64  |mono-*.-fb.*-lod|
00000030  65 20 73 61 6e 73 20 6d  6f 6e 6f 2d 2a 00 2d 66  |e sans mono-*.-f|
00000040  69 00 2a 2d 6c 6f 64 65  20 73 61 6e 73 20 6d 6f  |i.*-lode sans mo|
00000050  6e 6f 2d 2a 00 2d 66 62  69 00 2a 2d 6c 6f 64 65  |no-*.-fbi.*-lode|
00000060  20 73 61 6e 73 20 6d 6f  6e 6f 2d 2a 00 2d 64 65  | sans mono-*.-de|
00000070  70 74 68 00 33 32 00 2d  62 67 00 72 67 62 61 3a  |pth.32.-bg.rgba:|
00000080  30 30 30 30 2f 30 30 30  30 2f 30 30 30 30 2f 65  |0000/0000/0000/e|
00000090  35 62 62 00 2d 66 67 00  23 62 63 63 00 2d 73 62  |5bb.-fg.#bcc.-sb|
000000a0  00 2d 73 72 00 2b 73 74  00 2d 73 6c 00 31 30 30  |.-sr.+st.-sl.100|
000000b0  30 30 30 00 2d 62 00 30  00 2d 74 6e 00 72 78 76  |000.-b.0.-tn.rxv|
000000c0  74 00                                             |t.|
000000c2
```

Note that between each token, there is a zero byte (hex `00`, shows up in the righthand ASCII view as a `.`) and not a space (hex `20`). The part that says `*-lode sans mono-*` is a single token, so arguments containing spaces are interpreted correctly.

Some apps fiddle with their own `cmdline` representation, and use spaces instead of zero-bytes. I don't know if it's the case with electron/spotify, but it may be.

Are these threads? Try entering Setup, then in Display Options enable "Show custom thread names" and "Display threads in a different color". This may produce better results (and in particular, they work nicely in tree view too).

**Comment by NougatRillettes** [comment]
Hi,

Nice catch, there is indeed some wrong 0x20 there.

Note however than no threads are shown on my previous screen.

Is there anything that can be done on htop side or can it only be solved by opening an issues at each misbehaving app's tracker ?

**Comment by hishamhm** [comment]
> Is there anything that can be done on htop side or can it only be solved by opening an issues at each misbehaving app's tracker ?

Nothing on htop's side, unfortunately, because tweaking htop to "fix" those apps will break other apps which use names with spaces...

**Comment by NougatRillettes** [comment]
Ok thanks for your quick answers. :)
