### ISSUE TITLE
Swap usage per process

### ISSUE THREAD

**Issue by fancywriter** [hishamhm/htop#655]
I don't know if it's even possible in linux, but would be great to have this feature: to see how much **physical** and **swap** memory every process use.

**Comment by rsaxvc** [comment]
On Linux, it's in /proc/#/status on the VmSwap line.

**Comment by hishamhm** [comment]
A PR for this is definitely welcome!

I'm closing this entry for now since the issues page keeps open bugs only; feature requests are filed in the [`feature requests`](https://github.com/hishamhm/htop/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22feature+request%22+) label. More info [here](https://github.com/hishamhm/htop/blob/master/CONTRIBUTING.md#feature-requests)! Thank you for the feedback!
