### ISSUE TITLE
show free/available ram

### ISSUE THREAD

**Issue by flip111** [hishamhm/htop#714]
I enabled the memory meter in text mode. I just see `Mem: 7.72G used: 4.68G buffers: 175M cache:1.67G`. Could a free/available ram be added to this list?

**Comment by hishamhm** [comment]
That would depend on what you mean by free. If it is "memory not used by the system in any way", that would be `total - used - buffers - cache`. If it is "memory available for processes when they ask for memory", that would be `total - used` (with some minor adjustments due to kernel buffers). For this reason, "free" is not an easy clear-cut metric. The bar-graph display makes this distinction easier to grasp (as you can both look to the black area of the bar and to the "not-green" area).

**Comment by flip111** [comment]
I usually like to know how much memory there is left to run more programs, so `memory available for processes when they ask for memory` is most interesting. A number would be best in my opinion. Thanks for the tip about the bar-graph, i think it's the best option at the moment.
