### ISSUE TITLE
[Request] Checking With VirusTotal

### ISSUE THREAD

**Issue by zero77** [hishamhm/htop#786]
Can you please hash check with VirusTotal and show the result, if there’s no match of the hash can you upload the file to be checked.

Also, if the date they were last checked was more than a weak can you reanalyse and display new results, this should be possible with the api they provide.
Thanks

https://developers.virustotal.com/v2.0/reference

![1](https://user-images.githubusercontent.com/16563034/39248831-0d89ad62-4895-11e8-8bb7-696211e69001.png)

**Comment by Explorer09** [comment]
The htop upstream here does not provide pre-built binaries, only source. So what do you need to check with VirusTotal and what's the purpose for the check?

**Comment by zero77** [comment]
@Explorer09 
I don’t think I explain this well but, I am meaning checking/scanning of running processes or services that are displayed in htop not htop itself.

Like Process Explorer for windows dose, in the image above.

**Comment by Explorer09** [comment]
I don't think such an online capability is possible with the current htop code structure. Besides, there are privacy concerns if we upload executables automatically to virus scanning sites. (And note that no antivirus is perfect; there are possibilities of false positives.)
Which goal are you trying to achieve when requesting this feature?

**Comment by zero77** [comment]
>Besides, there are privacy concerns if we upload executables automatically to virus scanning sites.

Yes, that’s a good point, may be if users are asked first if they want to upload the binarie.

>(And note that no antivirus is perfect; there are possibilities of false positives.)

yes, I completely agree, I have experienced this before, but VirusTotal checks results against 50 to 60 different AV products, there for limiting false positives. 

>Which goal are you trying to achieve when requesting this feature?

Ideally much the same as Process Explorer in the image above, where there is an extra column showing the results from VirusTotal, of the running processes and services.

So users can keep an eye on any unusual, back doored or malicious processes and services.

**Comment by Explorer09** [comment]
@zero77 I was asking what situation you are in for needing this feature, not just the feature's expected goal.

Because I personally don't like the idea of htop communicating with a proprietary service (it's better to be a external plugin if we were to implement it). Free software relies on openness of the source code and build procedures for security and trust, not on a proprietary antivirus service. In addition, most antivirus products can treat open source hacking tools (I mean monitoring such as VNC) as malware, it cannot distinguish legitimate *uses* of the tools from malicious ones. (And that's why I had a bad experience with them.)

I don't have the power to make decisions, but I personally won't be bothered to implement it.

**Comment by hishamhm** [comment]
This is clearly outside of the scope and goals of htop, so thanks for the suggestion, but no thanks!
