### ISSUE TITLE
viewing human readable sizes in the RES column

### ISSUE THREAD

**Issue by sixpointzero** [hishamhm/htop#791]
I'm using version 2.2.0 of htop.

The RES column doesn't show human readable sizes for all the tasks.

![res](https://user-images.githubusercontent.com/19494538/39588542-7d9ce77a-4eeb-11e8-9377-16b77c734e52.jpg)

Is this expected? I would prefer to see memory usage of each task in M or G.

**Comment by Explorer09** [comment]
Yes, it's expected. The memory columns default in KiB unit, and if the amount is less than 100000 KiB, then it'll show 5 digits without a unit suffix.

**Comment by sixpointzero** [comment]
Is there a reason for this inconsistency? I think a better approach would be to show sizes in K, M, and G depending on the amount of memory being used.

**Comment by Explorer09** [comment]
@sixpointzero It does show M, G, T and larger units. It's only in the K case that the unit is omitted.
It makes no sense to show memory amount lower than K since the operating system manages memory in _pages_, which is always a multiple of KiB's.

In the screenshot you attached, for example, you should interpret that `/sbin/init` uses 10372K resident memory, not 10372 bytes.

**Comment by sixpointzero** [comment]
@Explorer09 I get you and it might make sense technically but do you think it would be an aesthetic improvement if we display sizes less than 100000KiB with a 'K' suffix? Or, if we can't display K by default, how about adding an option to do it?

**Comment by Explorer09** [comment]
@sixpointzero And another reason is that `top` also omits the K suffix in these columns.
The option is left for you to implement. I personally won't get bothered.

**Comment by sixpointzero** [comment]
@Explorer09 Ok, thanks anyways for the help.

**Comment by hishamhm** [comment]
@sixpointzero Hi, htop author here. @Explorer09 explained the behavior, but to add to the reasoning: the goal was to use the least "screen real estate" possible there. While showing "K" could be nice for better understanding indeed, that means we would have to lose precision (`28472` in 5 columns would become `   28K` — given KiB's 1024-base, rational numbers won't make a lot of sense: what would `28.5K`mean?).

So I tried to at least give some human-readability through colors: the K's, M's, G's and T's each shows up in a specfic color (that's why in KiB view with `XXYYY`, the `XX` are the same color as `XXXM` in MiB view). I hope you'll eventually get used to spot the cyan numbers as "M" over time. :)
