### ISSUE TITLE
Setup - Meters: Delete key

### ISSUE THREAD

**Issue by TrainerRed151** [hishamhm/htop#957]
The 2017 13in Macbook Pro does not have a dedicated `Del` button.  As such, it is not possible to delete an entry in the Left or Right columns in the Meters menu in Setup.

**Comment by GrooverChris** [comment]
This is a common issue with Macs, but the usual solution is to hold ` fn ` when pressing the ` delete ` key.

Pressing ` delete ` will delete text in a backwards direction, like a standard ` <-- Backspace ` key does.
Pressing ` fn ` + ` delete ` will delete text forward of the cursor, like a standard ` Del ` key does.

Sharing because **htop** was the reason I specifically needed to know this myself.
Reference: https://support.apple.com/en-us/HT201236
Further troubleshooting: https://superuser.com/questions/1425758/fn-delete-on-mac-no-longer-works

**Comment by TrainerRed151** [comment]
That worked, thanks!
